version: '3.3'
services:
    zigbee2soco:
        build: .
        restart: always
        network_mode: host
        image: zigbee2soco
        stdin_open: true # docker run -i
        tty: true        # docker run -t
        environment:
          - PREFIX=zigbee/stereo
          - MQTT_HOST=localhost
          - MQTT_PORT=1883
          - MQTT_USER=minion
          - MQTT_PASS=banana
